name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Export Google Application Credentials
      run: |
        echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > /tmp/credentials.json
        export GOOGLE_APPLICATION_CREDENTIALS=/tmp/credentials.json
      shell: bash

    - name: Authenticate with Google Cloud
      run: gcloud auth activate-service-account --key-file=/tmp/credentials.json

    - name: Deploy Application
      run: |
        # Seu comando de deploy aqui
        gcloud app deploy
